# These are supported funding model platforms

custom: ["https://www.paypal.me/tallguyjenks"]

patreon: ["https://www.patreon.com/bryanjenks?fan_landing=true"]

custom: ["https://www.buymeacoffee.com/tallguyjenks"]
